Repository openshift/origin-web-console, pull requests merged in 2018-09, with the labels that each got.

#3060 Fix wrong 'archiveLink' for operations user
  app/index.html
  app/scripts/directives/logViewer.js
  app/scripts/services/aggregatedLoggingService.js
  app/scripts/services/logLinks.js
  app/views/directives/logs/_log-viewer.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
  dist/scripts/vendor.js
Labels: lgtm, size/L

#3057 Update key-validator regexp for key-value-editor
  app/views/browse/build-config.html
  app/views/create/fromimage.html
  app/views/directives/deploy-image.html
  app/views/directives/edit-environment-variables.html
  app/views/directives/edit-lifecycle-hook.html
  app/views/edit/build-config.html
  app/views/edit/deployment-config.html
  dist/scripts/templates.js
  dist/scripts/vendor.js
  package-lock.json
Labels: lgtm, size/XXL

#3071 Update environment variables validation for BC
  app/views/browse/build-config.html
  app/views/edit/build-config.html
  dist/scripts/templates.js
  package-lock.json
Labels: lgtm, size/M

#3075 Bug 1607150 - Additional fix for: UI Timeout causing IE 11 to automatically log out
  app/scripts/app.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#3076 Bug 1607150 - Additional fix for: UI Timeout causing IE 11 to automatically log out
  app/scripts/app.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: size/XS

#3078 Add support for AMQ 7 Broker in Java console (3.10)
  .gitignore
  dist.java/java/404.html
  dist.java/java/app-6c16cfd8a8.js
  dist.java/java/app-747a60cd4f.js
  dist.java/java/index.html
  dist.java/java/libs-301d12fa8a.js
  dist.java/java/libs-a15571faaa.js
  dist.java/java/style.css
  dist.java/java/version.json
  dist/scripts/vendor.js
  hack/install-deps.sh
Labels: lgtm, size/M

#3077 Add support for AMQ 7 Broker in Java console (3.9)
  .gitignore
  dist.java/java/404.html
  dist.java/java/app-6c16cfd8a8.js
  dist.java/java/app-747a60cd4f.js
  dist.java/java/index.html
  dist.java/java/libs-301d12fa8a.js
  dist.java/java/libs-a15571faaa.js
  dist.java/java/style.css
  dist.java/java/version.json
  dist/scripts/vendor.js
  hack/install-deps.sh
Labels: lgtm, size/M

#3079 Add support for AMQ 7 Broker in Java console (3.11)
  .gitignore
  dist.java/java/404.html
  dist.java/java/app-6c16cfd8a8.js
  dist.java/java/app-747a60cd4f.js
  dist.java/java/index.html
  dist.java/java/libs-301d12fa8a.js
  dist.java/java/libs-a15571faaa.js
  dist.java/java/style.css
  dist.java/java/version.json
  dist/scripts/vendor.js
  hack/install-deps.sh
Labels: lgtm, size/M
