Repository openshift/origin-web-console, pull requests merged in 2018-11, with the labels that each got.

#3088 [enterprise-3.9] fix kibana archive link for operations
  README.md
  app/index.html
  app/scripts/directives/logViewer.js
  app/scripts/services/aggregatedLoggingService.js
  app/scripts/services/logLinks.js
  dist/scripts/scripts.js
Labels: lgtm, size/L

#3087 [enterprise-3.10] fix kibana archive link for operations
  app/index.html
  app/scripts/directives/logViewer.js
  app/scripts/services/aggregatedLoggingService.js
  app/scripts/services/logLinks.js
  dist/scripts/scripts.js
Labels: lgtm, size/L

#3097 Bug 1652645 - Webhook urls in configuration page are invalid with undefined included
  app/scripts/directives/util.js
  app/scripts/filters/resources.js
  app/scripts/services/secrets.js
  app/views/browse/build-config.html
  app/views/directives/_copy-webhook-trigger.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#3100 Bug 1652645 - follow up
  app/scripts/services/secrets.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#3098 [enterprise-3.10] Bug 1652645 - Webhook urls in configuration page are invalid with undefined included
  app/scripts/directives/util.js
  app/scripts/filters/resources.js
  app/scripts/services/secrets.js
  app/views/browse/build-config.html
  app/views/directives/_copy-webhook-trigger.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M
