Repository openshift/origin-web-console, pull requests merged in 2018-07, with the labels that each got.

#3036 Prefer bower from node_modules directory
  dist/scripts/vendor.js
  hack/install-deps.sh
Labels: lgtm, size/S

#2823 Update missing canI build/log resource for buildConfig page
  app/scripts/controllers/buildConfig.js
  app/views/browse/build-config.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/S

#2842 Update directive/addConfigToApplication to use APIService.objectToResourceGroupVersion
  app/scripts/directives/addConfigToApplication.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#3004 Added PVC Expand functionality in Storage tab
  app/index.html
  app/scripts/controllers/modals/editPvcModal.js
  app/scripts/controllers/persistentVolumeClaim.js
  app/scripts/directives/editPvc.js
  app/views/browse/persistent-volume-claim.html
  app/views/modals/edit-pvc-resource.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/XL

#3040 Bug fixes for Expand PVC
  app/scripts/controllers/modals/editPvcModal.js
  app/scripts/controllers/persistentVolumeClaim.js
  dist/scripts/scripts.js
Labels: lgtm, size/M

#3041 Bug 1607150 - UI Timeout causing IE 11 to automatically log out
  app/scripts/app.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#3042 Bug 1607305 - Adjust log viewer to handle multiline and non-newline terminated responses
  app/scripts/directives/logViewer.js
  dist/scripts/scripts.js
Labels: lgtm, size/M
