Repository openshift/origin-web-console, pull requests merged in 2018-08, with the labels that each got.

#3047 [enterprise-3.10] Bug 1607150 - UI Timeout causing IE 11 to automatically log out
  app/scripts/app.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: lgtm, size/S

#3052 Update key-validator regexp for key-value-editor
  app/views/browse/build-config.html
  app/views/create/fromimage.html
  app/views/directives/deploy-image.html
  app/views/directives/edit-environment-variables.html
  app/views/directives/edit-lifecycle-hook.html
  app/views/edit/build-config.html
  app/views/edit/deployment-config.html
  dist/scripts/templates.js
Labels: lgtm, size/M

#3053 Bug[1608289, 1610739] - Fixes for expand pvc
  app/scripts/controllers/modals/editPvcModal.js
  app/views/modals/edit-pvc-resource.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/S

#3054 Change logo and favicon and remove logo from About and update link
  app/images/favicon.ico
  app/images/favicon.png
  app/images/logo-okd.svg
  app/styles/_navbar-vertical.less
  app/views/about.html
  dist/images/favicon.ico
  dist/images/favicon.png
  dist/images/logo-okd.svg
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/L

#3059 Bug 1614683 - Revert branding changes on enterprise branch
  app/images/favicon.ico
  app/images/favicon.png
  app/styles/_navbar-vertical.less
  app/views/about.html
  dist/images/favicon.ico
  dist/images/favicon.png
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/L

#3062 [Bug 1608289] Expand button should be enabled as long as the size don…
  app/scripts/controllers/modals/editPvcModal.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: lgtm, size/XXL

#3046 [enterprise-3.9] Bug 1607150 - UI Timeout causing IE 11 to automatically log out
  app/scripts/app.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: do-not-merge/hold, lgtm, size/S

#3066 Update dist
  dist/scripts/vendor.js
Labels: lgtm, size/L

#3067 No longer post token for kibana
  app/scripts/directives/logViewer.js
  app/scripts/services/logLinks.js
  app/views/directives/logs/_log-viewer.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L
