Repository openshift/origin-web-console, pull requests merged in 2018-03, with the labels that each got.

#2860 Removing layout.attrs to reduce dependencies
  app/components/osc-webhook-triggers/osc-webhook-triggers.html
  app/index.html
  app/scripts/directives/actionChip.js
  app/styles/_catalog.less
  app/styles/_components.less
  app/styles/_core.less
  app/styles/_log.less
  app/styles/_membership.less
  app/styles/_overview.less
  app/styles/_pipeline.less
  app/views/_container-statuses.html
  app/views/_pod-template-container.html
  app/views/_volume-claim-templates.html
  app/views/browse/build-config.html
  app/views/browse/deployment-config.html
  app/views/browse/pod.html
  app/views/browse/service-instance.html
  app/views/builds.html
  app/views/catalog/catalog.html
  app/views/catalog/category-content.html
  app/views/deployments.html
  app/views/directives/_build-pipeline-expanded.html
  app/views/directives/deployment-donut.html
  app/views/directives/labels.html
  app/views/directives/pods-table.html
  app/views/logs/chromeless-build-log.html
  app/views/logs/chromeless-deployment-log.html
  app/views/logs/chromeless-pod-log.html
  app/views/membership.html
  app/views/quota.html
  app/views/service-instances.html
  bower.json
  dist/scripts/templates.js
  dist/styles/main.css
  dist/styles/vendor.css
Labels: lgtm, size/XL

#2849 Bump kubernetes-container-terminal to v3.0.0
  app/index.html
  app/scripts/controllers/pod.js
  app/styles/_container-terminal.less
  app/styles/_core.less
  bower.json
  dist/scripts/scripts.js
  dist/scripts/vendor.js
  dist/styles/main.css
  dist/styles/vendor.css
Labels: lgtm, size/XXL

#2817 Update createSecret directive to use getPreferredVersion
  app/scripts/directives/createSecret.js
  app/views/directives/create-secret.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/S

#2816 Update kve to use getPreferredVersion
  app/scripts/directives/keyValueEditor.js
  app/views/directives/key-value-editor.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2830 Update _container-statuses.html include to use getPreferredVersion for canI check
  app/scripts/directives/resources.js
  app/views/_container-statuses.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#2821 Update volumes directive to use getPreferredVersion
  app/scripts/directives/resources.js
  app/views/_volumes.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/S

#2820 Update monitoring controller to use getPreferredVersion
  app/scripts/controllers/monitoring.js
  app/views/monitoring.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2819 Update buildPipeline directive to use getPreferredVersion
  app/scripts/directives/buildPipeline.js
  app/views/directives/_build-pipeline-links.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#2818 Update lifecycle-hook directives to use getPreferredVersion
  app/scripts/directives/lifecycleHook.js
  app/views/directives/lifecycle-hook.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#2840 Fix potential apiVersion mismatch in directives/fromFile
  app/scripts/directives/fromFile.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#2867 Bug 1550797 - Should remove 'loading..' when browser non-existent image
  app/scripts/controllers/image.js
  app/views/browse/image.html
  app/views/browse/imagestream.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/S

#2827 Update list-row-actions include to use getPreferredVersion for canI checks
  app/scripts/directives/overview/listRow.js
  app/views/overview/_list-row-actions.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#2831 Fix comment to use correct config.local.js path
  app/config.js
Labels: lgtm, size/XS

#2843 Update pod controller to use objectToResourceGroupVersion when creating the debug pod
  app/scripts/controllers/pod.js
  dist/scripts/scripts.js
Labels: lgtm, size/S

#2870 Bug 1549450 - Better to use the same name for Clear filters, Clear Filter, Clear All Filters
  app/styles/_core.less
  app/views/browse/config-maps.html
  app/views/browse/routes.html
  app/views/browse/stateful-sets.html
  app/views/builds.html
  app/views/catalog/catalog.html
  app/views/catalog/category-content.html
  app/views/deployments.html
  app/views/directives/events.html
  app/views/images.html
  app/views/other-resources.html
  app/views/overview.html
  app/views/pods.html
  app/views/projects.html
  app/views/secrets.html
  app/views/service-instances.html
  app/views/services.html
  app/views/storage.html
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/M

#2873 Bug 1551991 - Make env name required when valueFrom item selected
  app/views/directives/key-value-editor.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2869 Bug 1550138 - Remove 5 minute warning for pods
  app/scripts/filters/resources.js
  dist/scripts/scripts.js
Labels: lgtm, size/L

#2874 Bump origin-web-common to 3.9.1
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/XS

#2829 Update _list-row-empty-state.html include to use getPreferredVersion for canI check
  app/scripts/directives/overview/listRow.js
  app/views/overview/_list-row-content.html
  app/views/overview/_list-row-empty-state.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/S

#2878 Fix bug where incorrect var resulted in wrong spacing left of hamburger
  app/styles/_navbar-vertical.less
  dist/styles/main.css
Labels: lgtm, size/XS

#2877 Bug 551667 - Overview support for daemon sets
  app/scripts/controllers/overview.js
  app/views/overview.html
  bower.json
  dist/scripts/scripts.js
  dist/scripts/templates.js
  dist/scripts/vendor.js
Labels: lgtm, size/XL

#2833 Fix potential mismatch in createSecret
  app/scripts/directives/createSecret.js
  dist/scripts/scripts.js
Labels: lgtm, size/M

#2838 Allow viewing mobile clients in the overview screen
  app/index.html
  app/scripts/app.js
  app/scripts/controllers/overview.js
  app/scripts/directives/overview/mobileClientRow.js
  app/views/overview.html
  app/views/overview/_mobile-client-row.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2887 Display routes including annotation on overview instead of default route
  app/scripts/controllers/overview.js
  app/scripts/services/routes.js
  app/styles/_overview.less
  app/views/overview.html
  app/views/overview/_networking.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
  dist/scripts/vendor.js
  dist/styles/main.css
  dist/styles/vendor.css
Labels: lgtm, size/XL

#2888 Bug 1551991 - Correctly clear key when another valueFrom resource selected
  app/scripts/directives/keyValueEditor.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#2891 Fix bug 1551503 - Add Donut char to Dashboard does not work
  dist.java/java/404.html
  dist.java/java/app-6c16cfd8a8.js
  dist.java/java/app-747a60cd4f.js
  dist.java/java/index.html
  dist.java/java/libs-301d12fa8a.js
  dist.java/java/libs-71c628aae9.js
  dist.java/java/style.css
  dist.java/java/version.json
  dist/scripts/vendor.js
  hack/install-deps.sh
Labels: lgtm, needs-ok-to-test, size/L

#2893 Fix for DISABLE_SERVICE_CATALOG_LANDING_PAGE = true when Set Home page is set to Project List
  app/scripts/app.js
  dist/scripts/scripts.js
Labels: lgtm, size/S

#2879 Create Opaque Secrets from File
  app/index.html
  app/scripts/directives/createSecret.js
  app/scripts/directives/editConfigMapOrSecret.js
  app/views/create-config-map.html
  app/views/directives/create-secret.html
  app/views/directives/edit-config-map-or-secret.html
  app/views/edit/config-map.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2901 Handle binary files when creating generic secrets
  app/scripts/directives/createSecret.js
  app/scripts/directives/editConfigMapOrSecret.js
  app/scripts/directives/oscFileInput.js
  app/scripts/filters/util.js
  app/scripts/services/secrets.js
  app/views/directives/create-secret.html
  app/views/directives/edit-config-map-or-secret.html
  app/views/directives/osc-file-input.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2902 Bug 1477133 - Show link to owner on pod env tab
  app/views/browse/pod.html
  dist/scripts/templates.js
Labels: lgtm, size/S

#2900 Fix bug "Open link in new tab" in right click menu jumps to home page
  app/scripts/controllers/monitoring.js
  app/scripts/directives/overview/listRow.js
  app/scripts/filters/resources.js
  app/scripts/services/navigate.js
  app/views/monitoring.html
  app/views/overview/_list-row-content.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#2905 Remove hawtio-core dependency
  .jshintrc
  app/index.html
  app/scripts/app.js
  bower.json
  dist/scripts/scripts.js
  dist/scripts/vendor.js
  dist/styles/vendor.css
  extensions/examples/online-extensions.js
  test/.jshintrc
  test/karma.conf.js
Labels: lgtm, size/XXL

#2906 Bug 1558863 - Fix bug editing empty config map
  app/scripts/directives/editConfigMapOrSecret.js
  dist/scripts/scripts.js
Labels: lgtm, size/S

#2904 Provide link to create pull secret to private repo image on the deploy image.
  app/scripts/directives/deployImage.js
  app/styles/_overlay-forms.less
  app/views/directives/deploy-image.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/M

#2911 Should use apis group for webhook URL as CLI
  app/scripts/filters/resources.js
  dist/scripts/scripts.js
Labels: lgtm, size/S

#2914 Load JS dependencies in correct order
  app/index.html
  bower.json
  dist/scripts/vendor.js
  dist/styles/vendor.css
Labels: lgtm, size/XXL

#2910 Remove autoprefixer as we're not benefitting from it
  Gruntfile.js
  package-lock.json
  package.json
Labels: lgtm, size/L

#2917 Fix bug where margin below h2s on overview was removed
  app/styles/_overview.less
  dist/styles/main.css
Labels: lgtm, size/S

#2918 Adding Container Platform branding and doc links for 3.10
  app/images/logo-OCP-console-hdr-stacked.svg
  app/images/logo-OCP-console-hdr-thin.svg
  app/scripts/constants.js
  app/styles/_navbar-vertical.less
  dist.java/java/index.html
  dist/images/logo-OCP-console-hdr-stacked.svg
  dist/images/logo-OCP-console-hdr-thin.svg
  dist/scripts/scripts.js
  dist/styles/main.css
  hack/install-deps.sh
Labels: lgtm, size/M

#2916 Handle UTF-8 BOM when decoding secrets for display
  app/scripts/services/secrets.js
  dist/scripts/scripts.js
Labels: lgtm, size/M

#2883 New markup structure and styles to support single and dual input rows with one or two control buttons
  app/components/osc-webhook-triggers/osc-webhook-triggers.html
  app/styles/_buttons.less
  app/styles/_core.less
  app/styles/_forms.less
  app/styles/_kve.less
  app/styles/_secrets.less
  app/styles/_variables.less
  app/views/directives/_edit-command.html
  app/views/directives/edit-environment-from.html
  app/views/directives/edit-environment-variables.html
  app/views/directives/key-value-editor.html
  app/views/directives/osc-secrets.html
  app/views/directives/osc-source-secrets.html
  app/views/edit/build-config.html
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/XL

#2909 [enterprise-3.9] Bug 1558863 - Fix bug editing empty config map
  app/scripts/directives/editConfigMap.js
  dist/scripts/scripts.js
Labels: lgtm, size/S

#2923 [enterprise-3.9] Overview support for daemon sets
  app/scripts/controllers/overview.js
  app/views/overview.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2927 [enterprise-3.6] Overview support for daemon sets
  app/scripts/controllers/overview.js
  app/views/overview.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2926 [enterprise-3.7] Overview support for daemon sets
  app/scripts/controllers/overview.js
  app/views/overview.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2924 [enterprise-3.8] Overview support for daemon sets
  app/scripts/controllers/overview.js
  app/views/overview.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2920 Bump npm dependencies
  package-lock.json
Labels: lgtm, size/XXL
