Repository openshift/origin-web-console, pull requests merged in 2018-02, with the labels that each got.

#2800 Check service classes to see if template service broker is enabled
  app/config.js
  app/index.html
  app/scripts/controllers/about.js
  app/scripts/services/catalog.js
  bower.json
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: lgtm, size/XL

#2801 Switch to div element to prevent undesired bottom margin within table cell
  app/views/service-instances.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2802 Fix bugzilla 1545011: cpu input disappears in edit autoscaler if value set to 0
  app/scripts/directives/oscAutoscaling.js
  app/views/edit/autoscaler.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/S

#2803 Switch catalog tab icon to pficon-catalog
  app/scripts/constants.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#2805 Bug 1545828: Labels for secrets are not displayed
  app/views/browse/secret.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2763 Resize terminal when nav is collapsed or expanded
  app/scripts/controllers/pod.js
  app/scripts/directives/nav.js
  dist/scripts/scripts.js
Labels: lgtm, size/L

#2807 Updates to membership page to prevent breaking. This is a back port of an initial fix that went in 3.7.
  app/styles/_membership.less
  app/views/membership.html
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/L

#2809 Bump catalog version to v3.9.0-alpha.15
  bower.json
  dist/styles/main.css
Labels: lgtm, size/XS

#2814 Update canI checks in build template
  app/scripts/controllers/build.js
  app/views/browse/build.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/S

#2812 Bump origin-web-catalog to v3.9.0-alpha.16
  bower.json
  dist/styles/main.css
Labels: lgtm, size/XS

#2787 [3.5] Fix Bug 1543402 - A-MQ Components not visible in Java Console when using IE11 browser
  dist.java/java/404.html
  dist.java/java/app-6c16cfd8a8.js
  dist.java/java/app-f38f1f8a14.js
  dist.java/java/img/icons.gif
  dist.java/java/index.html
  dist.java/java/libs-301d12fa8a.js
  dist.java/java/libs-cee83b5806.js
  dist.java/java/style.css
  dist.java/java/version.json
  hack/install-deps.sh
  package-lock.json
Labels: lgtm, size/XXL

#2810 Bump origin-web-common to 3.9.0-alpha.14
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/M

#2825 Update pod details include to use getPreferredVersion
  app/views/browse/_pod-details.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2828 Remove unused include views/overview/_service-header.html
  app/views/overview/_service-header.html
  dist/scripts/templates.js
Labels: lgtm, size/M

#2832 Bug 1547348 Use project annotation to determine logging data prefix
  app/scripts/directives/logViewer.js
  app/scripts/services/logLinks.js
  dist/scripts/scripts.js
Labels: lgtm, size/S

#2847 Hide the .project-list when filtered results are 0
  app/views/projects.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2848 Bump openshift-logos-icon to v1.4.0
  bower.json
  dist/styles/fonts/openshift-logos-icon.svg
  dist/styles/fonts/openshift-logos-icon.ttf
  dist/styles/fonts/openshift-logos-icon.woff
  dist/styles/main.css
Labels: lgtm, size/XS

#2844 Remove padding from form-group-action buttons so they will have spacing consistency with links that are separated with .action-divider
  app/components/osc-webhook-triggers/osc-webhook-triggers.html
  app/styles/_core.less
  app/styles/_forms.less
  app/views/directives/key-value-editor.html
  app/views/directives/osc-routing.html
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/M

#2837 bug 1547688. fix project prefix for archive link
  app/scripts/directives/logViewer.js
  app/scripts/services/logLinks.js
  dist/scripts/scripts.js
  dist/styles/fonts/openshift-logos-icon.svg
  dist/styles/fonts/openshift-logos-icon.ttf
  dist/styles/fonts/openshift-logos-icon.woff
  dist/styles/main.css
Labels: lgtm, size/S

#2850 Add Cordova color image
  app/images/logos/cordova.png
  app/scripts/constants.js
  dist/images/logos/cordova.png
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#2797 Create ability to read annotation accessMode from StorageClasses
  app/scripts/directives/oscPersistentVolumeClaim.js
  app/scripts/filters/resources.js
  app/views/directives/osc-persistent-volume-claim.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2854 Bug 1549097 - Update nav canI check
  app/scripts/directives/nav.js
  dist/scripts/scripts.js
Labels: lgtm, size/M

#2852 Prevent pod-template and section-label from abutting next to metrics …
  app/styles/_overview.less
  dist/styles/main.css
Labels: lgtm, size/S

#2855 [enterprise-3.7] Bug 1549097 - Update nav canI check
  app/scripts/directives/nav.js
  dist/scripts/scripts.js
Labels: lgtm, size/M

#2857 Bump origin-web-common to 3.9.0-rc.0
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/XS

#2799 BC's build secret destination dir label and help-text are not align properly
  app/styles/_secrets.less
  app/views/browse/build-config.html
  app/views/directives/osc-source-secrets.html
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/M

#2859 Bug 1527689 - Let users add the same PVC multiple times
  app/scripts/controllers/attachPVC.js
  app/views/attach-pvc.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#2861 Update version to 3.9.0
  bower.json
  package-lock.json
  package.json
Labels: lgtm, size/XS
