Repository openshift/origin-web-console, pull requests merged in 2018-04, with the labels that each got.

#2929 Virtual Machines in Overview
  app/index.html
  app/scripts/app.js
  app/scripts/controllers/overview.js
  app/scripts/directives/dropdownItem.js
  app/scripts/directives/optionalLink.js
  app/scripts/directives/overview/virtualMachineRow.js
  app/views/overview.html
  app/views/overview/_virtual-machine-row.html
  app/views/overview/_vm-status.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
  dist/scripts/vendor.js
  dist/styles/main.css
Labels: lgtm, size/XXL

#2464 Create dockercodnfigjson as default secret
  app/scripts/directives/createSecret.js
  app/scripts/services/secrets.js
  app/views/directives/create-secret.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#2937 Fix linter warnings in virtualMachineRow.js
  app/scripts/directives/overview/virtualMachineRow.js
  dist/scripts/scripts.js
Labels: lgtm, size/S

#2943 Update to v1beta1/PartialObjectMetadataList
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/XS

#2940 Bug 1564823 - Fix deploy image help link
  app/views/directives/deploy-image.html
  dist/scripts/templates.js
Labels: lgtm, size/S

#2944 [enterprise-3.9] Fall back to JSON when PartialObjectMetadataList not available
  bower.json
  dist/scripts/vendor.js
  dist/styles/main.css
Labels: lgtm, size/S

#2948 [enterprise-3.3] Sanitize HTML output for log viewer
  app/scripts/directives/logViewer.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: lgtm

#2949 [enterprise-3.4] Sanitize HTML output for log viewer
  app/scripts/directives/logViewer.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: lgtm

#2950 [enterprise-3.5] Sanitize HTML output for log viewer
  app/scripts/services/html.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: lgtm

#2951 [enterprise-3.6] Sanitize HTML output for log viewer
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/M

#2952 [enterprise-3.7] Sanitize HTML output for log viewer
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/M

#2955 Sanitize HTML output for log viewer
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/M

#2953 [enterprise-3.9] Sanitize HTML output for log viewer
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/M

#2945 Metrics for Virtual Machine rows
  app/views/overview/_virtual-machine-row.html
  dist/scripts/templates.js
Labels: lgtm

#2894 Console context switcher
  app/scripts/directives/nav.js
  app/styles/_application-launcher.less
  app/styles/_contextselector.less
  app/styles/_navbar-vertical.less
  app/styles/_variables.less
  app/styles/main.less
  app/views/directives/header/header.html
  bower.json
  dist/scripts/scripts.js
  dist/scripts/templates.js
  dist/scripts/vendor.js
  dist/styles/fonts/PatternFlyIcons-webfont.eot
  dist/styles/fonts/PatternFlyIcons-webfont.svg
  dist/styles/fonts/PatternFlyIcons-webfont.ttf
  dist/styles/fonts/PatternFlyIcons-webfont.woff
  dist/styles/main.css
  extensions/examples/online-extensions.css
Labels: lgtm, size/L

#2959 Bump openshift-logos-icon to v1.5.0
  bower.json
  dist/styles/fonts/openshift-logos-icon.svg
  dist/styles/fonts/openshift-logos-icon.ttf
  dist/styles/fonts/openshift-logos-icon.woff
  dist/styles/main.css
Labels: lgtm, size/S

#2941 add mssql svg
  app/images/logos/mssql.svg
  app/scripts/constants.js
  dist/images/logos/mssql.svg
  dist/scripts/scripts.js
Labels: lgtm, size/L

#2946 Virtual Machine uptime added
  app/scripts/directives/overview/virtualMachineRow.js
  app/views/overview/_virtual-machine-row.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/L

#2942 Add Xamarin color image
  app/images/logos/xamarin.svg
  app/scripts/constants.js
  dist/images/logos/xamarin.svg
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#2963 Empty value for VM guest OS is '--'
  app/views/overview/_virtual-machine-row.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2967 Fix scaling message for DaemonSet pod donut
  app/views/overview/_list-row-content.html
  app/views/overview/_list-row-expanded.html
  dist/scripts/templates.js
Labels: lgtm, size/M

#2971 [enterprise-3.6] Fix scaling message for DaemonSet pod donut
  app/views/overview/_list-row-content.html
  app/views/overview/_list-row-expanded.html
  dist/scripts/templates.js
  dist/styles/fonts/openshift-logos-icon.svg
  dist/styles/fonts/openshift-logos-icon.ttf
  dist/styles/fonts/openshift-logos-icon.woff
  dist/styles/main.css
Labels: lgtm, size/M

#2964 Fix margin for OVM Detail on Overview page
  app/scripts/directives/overview/virtualMachineRow.js
  app/styles/_virtual-machine-row.less
  app/views/overview/_virtual-machine-row.html
  app/views/overview/_vm-status.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
  dist/styles/main.css
Labels: lgtm, size/L

#2935 Publish kubevirt image for the kubevirt-apb to use
  app/images/logos/kubevirt.svg
  app/scripts/constants.js
  dist/images/logos/kubevirt.svg
  dist/scripts/scripts.js
Labels: lgtm, size/M

#2976 Bump openshift-logos-icon to v1.6 to add VM icons
  bower.json
  dist/styles/fonts/openshift-logos-icon.svg
  dist/styles/fonts/openshift-logos-icon.ttf
  dist/styles/fonts/openshift-logos-icon.woff
  dist/styles/main.css
Labels: lgtm, size/S

#2980 Bug 1571034 - Miss 'CURRENT/NEW TAGS' for image configuration in bc config page
  app/components/istag-select/istag-select.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2981 Change routes help link on browse page
  app/views/browse/service.html
  dist/scripts/templates.js
Labels: lgtm, size/XS
