Repository openshift/origin-web-console, pull requests merged in 2018-05, with the labels that each got.

#2986 Remove orphaned, broken scroll-shadows-horizontal-other mixin
  app/styles/_scroll-shadows-horizontal.less
Labels: lgtm, size/S

#2989 Bug 1575488 - Don't show duplicate key error when key is blank
  app/views/directives/edit-config-map-or-secret.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2987 Bug 1574869 - Fix runtime error creating webhook secret
  app/scripts/directives/createSecret.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#2994 Bug 1577359 - Check canCreate in projects empty state message
  app/views/projects.html
  dist/scripts/templates.js
Labels: lgtm, size/XS

#2998 Add HawtioExtension shim
  app/index.html
  app/scripts/services/shims/hawtioExtension.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: lgtm, size/M

#3003 Bug 1477133 - Show link to stateful set on pod env tab
  app/scripts/controllers/pod.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#3009 Virtual Machines UI turned off
  app/scripts/app.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS
