Repository openshift/origin-web-console, pull requests merged in 2019-07, with the labels that each got.

#3135 Bug 1722815: Handle other image name formats in overview
  app/scripts/filters/resources.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: bugzilla/valid-bug, lgtm, size/M

#3139 Bug 1689102: Bump kubernetes-container-terminal to v3.0.1 to pick up …
  app/index.html
  bower.json
  dist/scripts/vendor.js
  dist/styles/vendor.css
Labels: bugzilla/valid-bug, lgtm, size/XXL

#3138 Bug 1689101: Bump kubernetes-container-terminal to v3.0.1 to pick up …
  app/index.html
  app/scripts/controllers/pod.js
  app/styles/_container-terminal.less
  app/styles/_core.less
  bower.json
  dist/scripts/scripts.js
  dist/scripts/vendor.js
  dist/styles/main.css
  dist/styles/vendor.css
Labels: bugzilla/valid-bug, lgtm, size/XXL

#3140 Bug 1733806: Avoid runtime errors checking quota when processing template
  app/scripts/services/quota.js
  dist/scripts/scripts.js
Labels: bugzilla/valid-bug, lgtm, size/XS
