Repository openshift/origin-web-console, pull requests merged in 2019-01, with the labels that each got.

#3105 [enterprise-3.11] Bump PatternFly to v3.59.0 to pick up Bootstrap fixes
  Gruntfile.js
  bower.json
  dist/scripts/vendor.js
  dist/styles/fonts/PatternFlyIcons-webfont.eot
  dist/styles/fonts/PatternFlyIcons-webfont.svg
  dist/styles/fonts/PatternFlyIcons-webfont.ttf
  dist/styles/fonts/PatternFlyIcons-webfont.woff
  dist/styles/main.css
Labels: lgtm, size/XXL

#3082 [enterprise-3.11] Bug 1633285 - No secrets dropdown in buildconfig edit page if any of the secrets has no data
  app/scripts/services/secrets.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#3099 [enterprise-3.11] Bug 1652645 - Webhook urls in configuration page are invalid with undefined included
  app/scripts/directives/util.js
  app/scripts/filters/resources.js
  app/scripts/services/secrets.js
  app/views/browse/build-config.html
  app/views/directives/_copy-webhook-trigger.html
  dist/scripts/scripts.js
  dist/scripts/templates.js
Labels: lgtm, size/M

#3106 [enterprise-3.11] Bump lodash to 4.17.11
  bower.json
  dist/scripts/vendor.js
Labels: lgtm, size/XXL

#3109 Fix bug where polling quotas causes annoying toast notifications
  app/scripts/controllers/overview.js
  app/scripts/controllers/replicaSet.js
  app/scripts/controllers/statefulSet.js
  dist/scripts/scripts.js
Labels: lgtm, size/M

#3083 Bug 1633285 - No secrets dropdown in buildconfig edit page if any of the secrets has no data
  app/scripts/services/secrets.js
  dist/scripts/scripts.js
  dist/scripts/vendor.js
Labels: lgtm, size/M

#3110 Fix bug where Membership nav item disappears
  app/scripts/constants.js
  dist/scripts/scripts.js
Labels: lgtm, size/XS

#3111 [enterprise-3.11] Bug 1623338 - Include `.cluser.local` in service hostname
  app/views/browse/service.html
  dist/scripts/templates.js
Labels: lgtm, size/XS
